Repository operator-framework/operator-marketplace, pull requests merged in 2018-11, with the labels that each got.

#21 [tests] Fix datastore unit test case
  pkg/datastore/datastore_test.go
Labels: approved, lgtm, size/XS

#20 Introduce phased reconciliation process for CatalogSourceConfig objects
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/apis/marketplace/v1alpha1/zz_generated.deepcopy.go
  pkg/catalogsourceconfig/catalogsourceconfig.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/deleted.go
  pkg/catalogsourceconfig/factory.go
  pkg/catalogsourceconfig/failed.go
  pkg/catalogsourceconfig/handler.go
  pkg/catalogsourceconfig/initial.go
  pkg/catalogsourceconfig/reconciler.go
  pkg/catalogsourceconfig/succeeded.go
Labels: approved, lgtm, size/XL

#23 Refactor appregistry and datastore package
  pkg/appregistry/appregistry.go
  pkg/appregistry/client.go
  pkg/appregistry/client_test.go
  pkg/appregistry/mock_unmarshaller.go
  pkg/appregistry/unmarshaller.go
  pkg/catalogsourceconfig/configuring.go
  pkg/datastore/datastore.go
  pkg/datastore/datastore_test.go
  pkg/datastore/manifest.go
  pkg/datastore/metadata.go
  pkg/datastore/mock_unmarshaler.go
  pkg/datastore/unmarshaler.go
  pkg/datastore/unmarshaler_test.go
  pkg/operatorsource/downloading_test.go
Labels: approved, lgtm, size/L

#26 Update RBAC policy
  deploy/rbac.yaml
Labels: approved, lgtm, size/S

#25 Updating README to include flow description and deploy using OLM
  README.md
Labels: approved, lgtm, size/S

#28 Misc fixes
  pkg/catalogsourceconfig/factory.go
  pkg/catalogsourceconfig/handler.go
  pkg/catalogsourceconfig/initial.go
Labels: approved, lgtm, size/S

#24 Fix yaml parsing error
  Gopkg.lock
  pkg/catalogsourceconfig/configuring.go
  pkg/datastore/datastore.go
  pkg/datastore/datastore_test.go
  pkg/datastore/manifest.go
  pkg/datastore/metadata.go
  pkg/datastore/mock_unmarshaler.go
  pkg/datastore/unmarshaler.go
  pkg/datastore/unmarshaler_test.go
Labels: approved, lgtm, size/XL

#31 Make MemoryDatastore a Singleton
  pkg/datastore/datastore.go
  pkg/operatorsource/operatorsource.go
Labels: approved, lgtm, size/S

#30 Add marketplace csv
  README.md
  deploy/csv/marketplace.csv.yaml
Labels: approved, lgtm, size/L

#33 Improve crds
  deploy/catalogsourceconfig.crd.yaml
  deploy/operatorsource.crd.yaml
  pkg/apis/marketplace/v1alpha1/phase_types.go
Labels: approved, lgtm, size/L

#37 Update gopkg using latest version of dep
  Gopkg.lock
Labels: approved, lgtm, size/L

#34 Subscribe operator(s) to desired namespace(s)
  Gopkg.lock
  pkg/datastore/bundler.go
  pkg/datastore/crd.go
  pkg/datastore/crdmap.go
  pkg/datastore/csv.go
  pkg/datastore/csv_test.go
  pkg/datastore/csvmap.go
  pkg/datastore/datastore.go
  pkg/datastore/datastore_test.go
  pkg/datastore/decomposer.go
  pkg/datastore/manifest.go
  pkg/datastore/mock_unmarshaler.go
  pkg/datastore/testdata/rh-operators.yaml
  pkg/datastore/unmarshaler.go
  pkg/datastore/unmarshaler_test.go
  pkg/datastore/walker.go
Labels: approved, lgtm, size/XXL
