Repository operator-framework/operator-marketplace, pull requests merged in 2018-12, with the labels that each got.

#42 Reconcile OperatorSource Spec update
  pkg/apis/marketplace/v1alpha1/operatorsource_types.go
  pkg/datastore/datastore.go
  pkg/datastore/datastore_test.go
  pkg/datastore/testdata/source-1.yaml
  pkg/datastore/testdata/source-2.yaml
  pkg/operatorsource/downloading.go
  pkg/operatorsource/downloading_test.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/handler.go
  pkg/operatorsource/updated.go
  pkg/operatorsource/updated_test.go
  pkg/operatorsource/validating.go
Labels: approved, lgtm, size/XL

#29 Handle CatalogSourceConfig updates
  pkg/catalogsourceconfig/cache.go
  pkg/catalogsourceconfig/cache_test.go
  pkg/catalogsourceconfig/catalogsourcebuilder.go
  pkg/catalogsourceconfig/configmapbuilder.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/factory.go
  pkg/catalogsourceconfig/handler.go
  pkg/catalogsourceconfig/update.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/operatorsource/handler.go
Labels: approved, lgtm, size/XL

#43 Remove ravi from market place reviewers
  OWNERS
Labels: approved, lgtm, size/XS

#40 [docs] Setup and troubleshooting for operator artifacts
  README.md
  docs/how-to-upload-artifact.md
  docs/how-to-upload-manifest.md
  scripts/get-quay-token
  scripts/push-to-quay
Labels: approved, lgtm, size/L

#44 Add krizza to reviewers list
  OWNERS
Labels: approved, lgtm, size/XS

#38 [docs] Update README installation instructions
  README.md
Labels: approved, lgtm, size/M

#49 [bug] Update csv to use the expected service account and namespace
  deploy/marketplace.csv.yaml
Labels: approved, lgtm, size/XS

#47 Update upstream Dockerfile
  Dockerfile
Labels: approved, lgtm, size/XS

#48 [deploy] Add liveness and readiness probes
  cmd/manager/main.go
  deploy/marketplace.csv.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#50 [deploy] Add namespace yaml
  README.md
  deploy/marketplace.ns.yaml
Labels: approved, lgtm, size/XS

#52 Fix path issue for downstream repo
  Dockerfile.rhel7
Labels: approved, lgtm, size/XS

#57 Fix OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#55 [opsrc] Add downloaded manifest list to Status
  pkg/apis/marketplace/v1alpha1/operatorsource_types.go
  pkg/datastore/datastore.go
  pkg/operatorsource/downloading.go
  pkg/operatorsource/downloading_test.go
Labels: approved, lgtm, size/M

#60 Update .gitignore to include Jetbrain IDEs
  .gitignore
Labels: approved, lgtm, size/L

#46 Ensure datastore cache is in sync when marketplace operator restarts
  pkg/datastore/datastore.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/handler.go
  pkg/operatorsource/handler_test.go
  pkg/operatorsource/initial.go
  pkg/operatorsource/outofsync.go
  pkg/operatorsource/purging.go
  pkg/operatorsource/purging_test.go
  pkg/operatorsource/validating.go
  pkg/phase/phase.go
Labels: approved, lgtm, size/L

#58 Add run-e2e-job script
  Makefile
  scripts/run-e2e-job.sh
Labels: approved, lgtm, size/S

#53 [deploy] Update the marketplace csv for use with OLM.
  README.md
  deploy/crds/catalogsourceconfig.crd.yaml
  deploy/crds/operatorsource.crd.yaml
  deploy/examples/catalogsourceconfig.cr.yaml
  deploy/examples/operatorsource.cr.yaml
  deploy/marketplace.ns.yaml
  deploy/marketplace.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  deploy/role_binding.yaml
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/M

#59 [csc+opsrc] Introduce datastore label
  pkg/catalogsourceconfig/catalogsourcebuilder.go
  pkg/catalogsourceconfig/configuring.go
  pkg/operatorsource/catalogsourceconfigbuilder.go
  pkg/operatorsource/helper_test.go
Labels: approved, lgtm, size/M

#63 Run e2e-ci job
  Makefile
  scripts/run-e2e-job.sh
Labels: approved, lgtm, size/XS

#65 Improve naming of CRs
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/update.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/purging.go
  pkg/operatorsource/purging_test.go
  test/e2e/marketplace_test.go
Labels: approved, lgtm, size/M

#66 Make datastore access concurrent
  pkg/datastore/datastore.go
  pkg/datastore/metadata.go
  pkg/datastore/row.go
  pkg/operatorsource/outofsync.go
Labels: approved, lgtm, size/L

#70 [opsrc] Handle OperatorSource deletion
  pkg/apis/marketplace/v1alpha1/operatorsource_types.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/initial.go
Labels: approved, lgtm, size/L

#73 [opsrc] support for multiple operator source CR(s)
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
Labels: approved, lgtm, size/XS

#71 Keep datastore in sync with registry update(s)
  cmd/manager/main.go
  pkg/appregistry/client.go
  pkg/datastore/datastore.go
  pkg/datastore/row.go
  pkg/operatorsource/poller.go
  pkg/operatorsource/pollhelper.go
  pkg/operatorsource/syncer.go
Labels: approved, lgtm, size/L

#78 Format configuring.go imports correctly
  pkg/catalogsourceconfig/configuring.go
Labels: approved, lgtm, size/XS

#80 [opsrc] Add support to filter operator offering(s)
  pkg/catalogsourceconfig/catalogsourcebuilder.go
  pkg/catalogsourceconfig/configuring.go
  pkg/operatorsource/catalogsourceconfigbuilder.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/helper_test.go
  pkg/operatorsource/purging.go
  test/e2e/marketplace_test.go
Labels: approved, lgtm, size/L
