Repository operator-framework/operator-marketplace, pull requests merged in 2018-10, with the labels that each got.

#5 Filter by registry namespace
  deploy/operatorsource.cr.yaml
  pkg/apis/marketplace/v1alpha1/types.go
  pkg/appregistry/adapter.go
  pkg/appregistry/appregistry.go
  pkg/appregistry/appregistry_test.go
  pkg/appregistry/client.go
  pkg/appregistry/mock_adapter.go
  pkg/operatorsource/reconciler.go
Labels: size/M

#6 add documentation on how to push operator manifest to app registry
  docs/how-to-upload-manifest.md
Labels: size/L

#8 Update readme and remove pull secret
  README.md
  deploy/marketplace-pull-secret.yaml
Labels: lgtm, size/M

#9 Add Dockerfile to build without operator-sdk
  Dockerfile
  Makefile
Labels: size/S

#10 Create OWNERS
  OWNERS
Labels: size/XS

#7 Populate the ConfigMap with operator artifacts
  Dockerfile
  deploy/catalogsourceconfig.cr.yaml
  pkg/catalogsourceconfig/catalogsourceconfig.go
  pkg/catalogsourceconfig/handler.go
  pkg/operatorsource/handler.go
  pkg/stub/catalogsourceconfig_handler.go
  pkg/stub/handler.go
  tmp/build/Dockerfile
Labels: lgtm, size/L

#12 Add unit tests rule to Makefile.
  Makefile
Labels: size/XS

#13 Update Dockerfile base image
  Dockerfile
  tmp/build/Dockerfile
Labels: size/XS

#19 CatalogSourceConfig requires field "metadata.namespace"
  deploy/examples/catalogsourceconfig.cr.yaml
  deploy/examples/operatorsource.cr.yaml
Labels: approved, lgtm, size/XS

#18 OperatorSource reconciliation refactor
  Makefile
  pkg/apis/marketplace/v1alpha1/operatorsource.go
  pkg/apis/marketplace/v1alpha1/operatorsource_types.go
  pkg/apis/marketplace/v1alpha1/phase.go
  pkg/apis/marketplace/v1alpha1/phase_types.go
  pkg/apis/marketplace/v1alpha1/zz_generated.deepcopy.go
  pkg/operatorsource/catalogsourceconfigbuilder.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/downloading.go
  pkg/operatorsource/downloading_test.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/failed.go
  pkg/operatorsource/handler.go
  pkg/operatorsource/handler_test.go
  pkg/operatorsource/helper_test.go
  pkg/operatorsource/initial.go
  pkg/operatorsource/operatorsource.go
  pkg/operatorsource/phase/helper_test.go
  pkg/operatorsource/phase/phase.go
  pkg/operatorsource/phase/transitioner.go
  pkg/operatorsource/phase/transitioner_test.go
  pkg/operatorsource/reconciler.go
  pkg/operatorsource/succeeded.go
  pkg/operatorsource/validating.go
  pkg/phase/phase.go
  pkg/phase/transitioner.go
  pkg/phase/transitioner_test.go
Labels: approved, lgtm, size/XL
