Repository operator-framework/operator-marketplace, pull requests merged in 2019-08, with the labels that each got.

#231 Bug 1722096: fix panic when scale down of registry deployment fails
  pkg/catalogsourceconfig/registry.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#236 Bug 1737175: Do not hardcode GOOS/GOARCH
  build/build.sh
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#237 [proxy] Enable Proxy
  cmd/manager/main.go
  deploy/operator.yaml
  deploy/role.yaml
  manifests/05_role.yaml
  manifests/07_operator.yaml
  pkg/appregistry/appregistry.go
  pkg/catalogsourceconfig/succeeded.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/operatorsource/succeeded.go
  pkg/proxy/available.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/registry/registry.go
  pkg/watches/helpers.go
  pkg/watches/proxy_csc_mapper.go
  pkg/watches/proxy_opsrc_mapper.go
  test/e2e/main_test.go
  test/helpers/helpers.go
  test/testgroups/opsrccsctests.go
  test/testsuites/proxytests.go
Labels: approved, lgtm, size/XL

#242 [CA] Use Certificate Authority bundle
  deploy/configmap.yaml
  deploy/operator.yaml
  deploy/role.yaml
  manifests/05_role.yaml
  manifests/07_configmap.yaml
  manifests/08_operator.yaml
  manifests/09_clusteroperator.yaml
  pkg/certificateauthority/mount.go
  pkg/controller/add_configmap.go
  pkg/controller/configmap/configmap_controller.go
  pkg/registry/registry.go
Labels: approved, lgtm, size/L

#239 Bug 1732588: Stop scaling down registry deployment
  pkg/catalogsourceconfig/registry.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#241 Bug 1740824: Fix degraded status on upgrade
  cmd/manager/main.go
  deploy/operator.yaml
  deploy/role.yaml
  deploy/upstream/05_role.yaml
  deploy/upstream/08_operator.yaml
  manifests/05_role.yaml
  manifests/10_operator.yaml
  pkg/catalogsourceconfig/handler.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/operatorsource/handler.go
  pkg/status/status.go
  pkg/status/syncutils.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#244 Revert “[CA] Use Certificate Authority bundle"
  deploy/configmap.yaml
  deploy/operator.yaml
  deploy/role.yaml
  manifests/05_role.yaml
  manifests/07_configmap.yaml
  manifests/07_operator.yaml
  manifests/08_clusteroperator.yaml
  pkg/certificateauthority/mount.go
  pkg/controller/add_configmap.go
  pkg/controller/configmap/configmap_controller.go
  pkg/registry/registry.go
Labels: lgtm, size/L

#245 [CA] Use Certificate Authority bundle
  deploy/configmap.yaml
  deploy/operator.yaml
  deploy/role.yaml
  manifests/05_role.yaml
  manifests/07_configmap.yaml
  manifests/08_operator.yaml
  manifests/09_clusteroperator.yaml
  pkg/certificateauthority/caconfigmap.go
  pkg/certificateauthority/handler.go
  pkg/controller/add_configmap.go
  pkg/controller/configmap/configmap_controller.go
  pkg/registry/registry.go
Labels: approved, lgtm, size/L

#240 Bug 1739562: [migration] Don't kill due to invalid subscription
  pkg/migrator/migrator.go
  test/helpers/helpers.go
  test/testgroups/migrationtests.go
  test/testsuites/migrationtests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#229 Bug 1711070 - Set container resource requests
  deploy/operator.yaml
  deploy/upstream/08_operator.yaml
  manifests/08_operator.yaml
  pkg/registry/registry.go
Labels: approved, lgtm, size/S

#232 Bug 1732577: Handle delete events while operator is restarting
  pkg/apis/operators/shared/shared.go
  pkg/apis/operators/v1/operatorsource_types.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/defaults/defaults.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/failed.go
  pkg/operatorsource/handler.go
  pkg/operatorsource/handler_test.go
  pkg/operatorsource/initial.go
  pkg/operatorsource/otherns.go
  pkg/operatorsource/outofsync.go
  pkg/operatorsource/purging.go
  pkg/operatorsource/purging_test.go
  pkg/operatorsource/reconciler.go
  pkg/operatorsource/succeeded.go
  pkg/operatorsource/validating.go
  scripts/e2e-tests.sh
  test/helpers/helpers.go
  test/testsuites/defaultopsrctests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L
