Repository operator-framework/operator-marketplace, pull requests merged in 2019-11, with the labels that each got.

#261 add version option
  build/build.sh
  cmd/manager/main.go
  pkg/version/version.go
Labels: approved, lgtm, ok-to-test, size/S

#259 Bug 1768483: Limit Cardinality of Marketplace quay metrics
  deploy/prometheus_rule.yaml
  manifests/12_prometheus_rule.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#267 Updating CatalogSourceConfig CRD hyperlink to point to the correct cr…
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#268 Bug 1767547: Don't create invalid deployment
  deploy/role.yaml
  deploy/upstream/05_role.yaml
  manifests/05_role.yaml
  pkg/grpccatalog/grpccatalog.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/helper_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#263 Bug 1762006: Assume available status is true without defaults
  pkg/operatorhub/operatorhub.go
  pkg/status/status.go
  test/testsuites/operatorhubtests.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#271 Bug 1775245: Schedule registry pods onto linux nodes only
  pkg/registry/registry.go
  pkg/registry/registry_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S
