Repository operator-framework/operator-marketplace, pull requests merged in 2019-05, with the labels that each got.

#171 [docs] Add troubleshooting guide
  docs/images/OperatorHubError.png
  docs/troubleshooting.md
Labels: approved, lgtm, size/L

#166 [e2e] Add tests for invalid OperatorSources
  test/e2e/main_test.go
  test/testgroups/nosetuptests.go
  test/testsuites/invalidopsrctests.go
Labels: approved, lgtm, size/L

#175 [e2e] Make CLI output for tests more verbose
  scripts/e2e-tests.sh
Labels: approved, lgtm, size/XS

#170 [e2e] Add opsrc delete test
  test/helpers/helpers.go
  test/testgroups/nosetuptests.go
  test/testsuites/opsrcdeletetests.go
Labels: approved, lgtm, size/M

#174 [docs] Document Conflicting Package Name Behavior
  docs/troubleshooting.md
Labels: approved, lgtm, size/S

#178 Fix tolerations
  deploy/operator.yaml
  manifests/10_operator.yaml
Labels: approved, lgtm, size/S

#179 Bug 1706867: ClusterOperator degrading on exit
  cmd/manager/main.go
  pkg/status/status.go
Labels: approved, lgtm, size/M

#180 Bug 1693964: Log reconciliation update error
  pkg/catalogsourceconfig/handler.go
  pkg/operatorsource/handler.go
Labels: approved, lgtm, size/XS

#151 [e2e] csc with non-existent package
  test/helpers/helpers.go
  test/testgroups/operatorsourcetests.go
  test/testsuites/const.go
  test/testsuites/cscpackagetests.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/opsrccreationtests.go
  test/testsuites/opsrcdeletetests.go
Labels: approved, lgtm, size/L

#183 [status] Reformat status comments
  cmd/manager/main.go
  pkg/status/status.go
  pkg/status/syncratio.go
Labels: approved, lgtm, size/M

#185 Bug 1708503: Fix missing openapi CRD descriptions
  deploy/crds/operators_v1_catalogsourceconfig_crd.yaml
  deploy/crds/operators_v1_operatorsource_crd.yaml
  deploy/upstream/02_catalogsourceconfig.crd.yaml
  deploy/upstream/03_operatorsource.crd.yaml
  manifests/02_catalogsourceconfig.crd.yaml
  manifests/03_operatorsource.crd.yaml
Labels: approved, lgtm, size/XS

#184 [status] Rely on stopCh to stop reporting status
  cmd/manager/main.go
Labels: approved, lgtm, size/M

#147 Migrate to fake client for OperatorSource unit tests
  Makefile
  pkg/client/client.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/downloading_test.go
  pkg/operatorsource/handler_test.go
  pkg/operatorsource/helper_test.go
  pkg/operatorsource/purging_test.go
Labels: approved, lgtm, size/L

#187 [status] Handle unset RELEASE_VERSION env var
  pkg/status/status.go
Labels: approved, lgtm, size/XS

#177 [e2e] Use asserts/require instead of error checks
  docs/e2e-testing.md
  test/testgroups/operatorsourcetests.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/invalidopsrctests.go
  test/testsuites/opsrccreationtests.go
Labels: approved, lgtm, size/L

#176 [docs] Fix troubleshooting doc
  docs/troubleshooting.md
Labels: approved, lgtm, size/M

#189 Update approvers list in OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#186 [e2e] Check ClusterOperator Status upon initialization
  test/e2e/main_test.go
  test/testgroups/clusteroperatortests.go
  test/testsuites/clusteroperatorstatustests.go
Labels: approved, lgtm, size/M

#190 [e2e] Update error reporting for e2e pkg tests
  test/testsuites/cscpackagetests.go
Labels: approved, lgtm, size/S

#194 [doc] Fix command to delete deployment
  CONTRIBUTING.md
Labels: approved, lgtm, size/XS

#191 Combine Downloading and Configuring Phases
  pkg/operatorsource/appregistryhelper.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/downloading.go
  pkg/operatorsource/downloading_test.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/validating.go
  pkg/phase/phase.go
  test/testsuites/invalidopsrctests.go
Labels: approved, lgtm, size/XL

#193 [doc] Fix broken links in troubleshooting doc
  docs/troubleshooting.md
Labels: approved, lgtm, size/XS
