Repository operator-framework/operator-marketplace, pull requests merged in 2019-02, with the labels that each got.

#104 Add upstream deployment
  README.md
  deploy/marketplace.v0.0.1.clusterserviceversion.yaml
  deploy/upstream/01_namespace.yaml
  deploy/upstream/02_catalogsourceconfig.crd.yaml
  deploy/upstream/03_operatorsource.crd.yaml
  deploy/upstream/04_service_account.yaml
  deploy/upstream/05_role.yaml
  deploy/upstream/06_role_binding.yaml
  deploy/upstream/07_operator.yaml
Labels: approved, lgtm, size/L

#106 Generate typed clientset for marketplace type(s)
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/apis/marketplace/v1alpha1/operatorsource_types.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/doc.go
  pkg/client/clientset/versioned/scheme/doc.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/marketplace/v1alpha1/catalogsourceconfig.go
  pkg/client/clientset/versioned/typed/marketplace/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/marketplace/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/marketplace/v1alpha1/marketplace_client.go
  pkg/client/clientset/versioned/typed/marketplace/v1alpha1/operatorsource.go
Labels: approved, lgtm, size/XL

#103 [opsrc] Fix OperatorSource reconciliation error
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/operatorsource/configuring.go
Labels: approved, lgtm, size/S

#110 Add authentication to appregistry
  README.md
  deploy/role.yaml
  deploy/upstream/05_role.yaml
  docs/how-to-authenticate-private-repositories.md
  manifests/05_role.yaml
  pkg/apis/marketplace/v1alpha1/operatorsource_types.go
  pkg/apis/marketplace/v1alpha1/zz_generated.deepcopy.go
  pkg/appregistry/appregistry.go
  pkg/catalogsourceconfig/registry.go
  pkg/operatorsource/appregistryhelper.go
  pkg/operatorsource/downloading.go
  pkg/operatorsource/downloading_test.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/pollhelper.go
Labels: approved, lgtm, size/L

#113 [tests] Update run-e2e-job.sh permissions
  scripts/run-e2e-job.sh
Labels: approved, lgtm, size/XS

#111 Fix some doc links
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#115 [csc] Handle invalid packages
  pkg/catalogsourceconfig/configuring.go
Labels: approved, lgtm, size/S

#114 Fix update sync with Quay
  pkg/catalogsourceconfig/registry.go
Labels: approved, lgtm, size/S

#112 Update README with newly created OperatorSource
  README.md
  deploy/examples/catalogsourceconfig.cr.yaml
  deploy/examples/community.operatorsource.cr.yaml
  deploy/examples/upstream.operatorsource.cr.yaml
Labels: approved, lgtm, size/M

#117 [opsrc] Do not delete csc during purge
  pkg/operatorsource/configuring.go
  pkg/operatorsource/purging.go
  pkg/operatorsource/purging_test.go
Labels: approved, lgtm, size/M

#118 Remove Dependency on Owner References
  manifests/05_role.yaml
  pkg/catalogsourceconfig/catalogsourcebuilder.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/deleted.go
  pkg/catalogsourceconfig/deploymentbuilder.go
  pkg/catalogsourceconfig/podtemplatebuilder.go
  pkg/catalogsourceconfig/registry.go
  pkg/catalogsourceconfig/rolebindingbuilder.go
  pkg/catalogsourceconfig/rolebuilder.go
  pkg/catalogsourceconfig/serviceaccountbuilder.go
  pkg/catalogsourceconfig/servicebuilder.go
  pkg/operatorsource/catalogsourceconfigbuilder.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/deleted.go
Labels: approved, lgtm, size/L

#120 [docs] Update the README
  README.md
  docs/how-to-upload-artifact.md
  scripts/get-quay-token
  scripts/push-to-quay
Labels: approved, lgtm, size/L
