Repository operator-framework/operator-marketplace, pull requests merged in 2019-06, with the labels that each got.

#182 [e2e] OperatorSource with conflicting packages
  test/helpers/helpers.go
  test/testgroups/operatorsourcetests.go
  test/testsuites/opsrcdeletetests.go
  test/testsuites/packagestests.go
Labels: approved, lgtm, size/M

#201 [e2e] Enable tests to run against minikube
  Makefile
  scripts/e2e-tests.sh
  test/e2e/main_test.go
Labels: approved, lgtm, size/S

#202 [e2e] Modularize waiting for opsrc creation
  test/helpers/helpers.go
  test/testsuites/invalidopsrctests.go
Labels: approved, lgtm, size/M

#196 [status] Ensure CO status messages are not empty
  pkg/status/status.go
Labels: approved, lgtm, size/S

#198 OperatorSource configuring reconciler directly creates datastore CatalogSource
  README.md
  cmd/manager/main.go
  deploy/role.yaml
  deploy/upstream/05_role.yaml
  docs/troubleshooting.md
  manifests/05_role.yaml
  pkg/apis/operators/v1/catalogsourceconfig_types.go
  pkg/builders/builders.go
  pkg/builders/catalogsourcebuilder.go
  pkg/builders/deploymentbuilder.go
  pkg/builders/rolebindingbuilder.go
  pkg/builders/rolebuilder.go
  pkg/builders/serviceaccountbuilder.go
  pkg/builders/servicebuilder.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/deleted.go
  pkg/catalogsourceconfig/triggerer.go
  pkg/catalogsourceconfig/update.go
  pkg/client/client.go
  pkg/datastore/datastore.go
  pkg/grpccatalog/grpccatalog.go
  pkg/operatorsource/catalogsourceconfigbuilder.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/helper_test.go
  pkg/operatorsource/poller.go
  pkg/operatorsource/pollhelper.go
  pkg/operatorsource/purging.go
  pkg/operatorsource/syncer.go
  pkg/registry/registry.go
  test/helpers/helpers.go
  test/testsuites/invalidopsrctests.go
  test/testsuites/opsrccreationtests.go
  test/testsuites/opsrcdeletetests.go
  test/testsuites/packagestests.go
Labels: approved, lgtm, size/XXL

#206 [docs] Update uninstall flow to exclude csc
  README.md
Labels: approved, lgtm, size/M

#197 [csc] Update CSC to specify a source name
  README.md
  deploy/crds/operators_v2_catalogsourceconfig_crd.yaml
  deploy/examples/catalogsourceconfig.cr.yaml
  deploy/upstream/02_catalogsourceconfig.crd.yaml
  docs/csc-source-resolution.md
  manifests/02_catalogsourceconfig.crd.yaml
  pkg/apis/operators/v2/catalogsourceconfig_types.go
  pkg/catalogsourceconfig/cache.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/syncer.go
  pkg/catalogsourceconfig/triggerer.go
  pkg/datastore/datastore.go
  pkg/datastore/datastore_test.go
  pkg/datastore/metadata.go
  pkg/datastore/update_result.go
  pkg/grpccatalog/grpccatalog.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/poller.go
  pkg/operatorsource/syncer.go
  pkg/registry/registry.go
  test/testsuites/packagestests.go
Labels: approved, lgtm, size/XL

#209 [e2e] Fix variable name
  test/e2e/main_test.go
Labels: approved, lgtm, size/XS

#205 Bug 1717439: [status] Populate RelatedObjects
  pkg/status/status.go
  test/testsuites/clusteroperatorstatustests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
