Repository operator-framework/operator-marketplace, pull requests merged in 2019-04, with the labels that each got.

#148 [docs] Remove contributing section from README
  CONTRIBUTING.md
  README.md
  deploy/examples/cvo.override.yaml
Labels: approved, lgtm, size/S

#160 [docs] Reorganize README to make it easier to read
  README.md
Labels: approved, lgtm, size/M

#161 [e2e] Refactor and documentation
  README.md
  docs/e2e-testing.md
  test/e2e/csc_tests.go
  test/e2e/helpers.go
  test/e2e/main_test.go
  test/e2e/marketplace_test.go
  test/helpers/helpers.go
  test/testgroups/operatorsourcetests.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/opsrccreationtests.go
Labels: approved, lgtm, size/XL

#159 [docs] Fix links for OperatorSource and CatalogSourceConfig
  README.md
Labels: approved, lgtm, size/XS

#158 [e2e] fix wrong csc kind
  test/testsuites/csctargetnamespacetests.go
Labels: approved, lgtm, size/XS

#149 Bug 1693375: [csc] Fix operator-registry command
  pkg/catalogsourceconfig/registry.go
Labels: approved, lgtm, size/M

#162 [docs] consolidating required fields for embedded and io
  docs/marketplace-required-csv-annotations.md
Labels: approved, lgtm, size/L

#144 Bug 1688540: address validation errors
  deploy/crds/operators_v1_catalogsourceconfig_crd.yaml
  deploy/crds/operators_v1_operatorsource_crd.yaml
  deploy/role_binding.yaml
  deploy/upstream/02_catalogsourceconfig.crd.yaml
  deploy/upstream/03_operatorsource.crd.yaml
  deploy/upstream/06_role_binding.yaml
  manifests/02_catalogsourceconfig.crd.yaml
  manifests/03_operatorsource.crd.yaml
  manifests/06_role_binding.yaml
Labels: approved, lgtm, size/M

#157 [docs] Clarify community vs upstream-community OperatorSources
  README.md
  deploy/upstream/07_upstream_operatorsource.cr.yaml
  deploy/upstream/08_operator.yaml
Labels: approved, lgtm, size/S

#167 [e2e] Add CSC test where namespace != targetNamespace
  test/helpers/helpers.go
  test/testgroups/operatorsourcetests.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/opsrccreationtests.go
Labels: approved, lgtm, size/L

#173 Add node-selector annotation to namespace
  deploy/marketplace.ns.yaml
  manifests/01_namespace.yaml
Labels: approved, lgtm, size/XS

#165 Bug 1700416:[status] Fix Status Reporting
  pkg/status/status.go
  pkg/status/syncratio.go
  pkg/status/syncutils.go
Labels: approved, lgtm, size/L
