Repository operator-framework/operator-marketplace, pull requests merged in 2019-09, with the labels that each got.

#246 Bug 1732164: Report Failing OperatorSource Data
  deploy/marketplace.ns.yaml
  deploy/prometheus_rule.yaml
  deploy/service.yaml
  deploy/service_monitor.yaml
  manifests/01_namespace.yaml
  manifests/08_service.yaml
  manifests/09_operator.yaml
  manifests/10_clusteroperator.yaml
  manifests/11_service_monitor.yaml
  manifests/12_prometheus_rule.yaml
  pkg/appregistry/appregistry.go
  pkg/metrics/metrics.go
  pkg/metrics/roundtripper.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#251 Race condition in config test
  test/testsuites/operatorhubtests.go
Labels: approved, lgtm, size/S

#252 Bug 1750654: The phase message of csc won't change when the env changed
  pkg/catalogsourceconfig/configuring.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/packagestests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#248 Fix broken links - OLM Documentation was replaced by doc
  CONTRIBUTING.md
  README.md
  docs/troubleshooting.md
Labels: approved, lgtm, size/XS

#250 [deploy] Sync deploy and manifest dirs
  deploy/service_monitor.yaml
Labels: approved, lgtm, size/M

#253 Bug 1732164: Rename marketplace rules
  deploy/prometheus_rule.yaml
  manifests/12_prometheus_rule.yaml
Labels: approved, bugzilla/valid-bug, lgtm, size/XS
