Repository operator-framework/operator-marketplace, pull requests merged in 2019-03, with the labels that each got.

#119 Fix upstream and sdk cluster role
  deploy/role.yaml
  deploy/upstream/05_role.yaml
Labels: approved, lgtm, size/XS

#125 Bug 1685066: Fix OperatorSource sync
  pkg/catalogsourceconfig/cache.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/syncer.go
Labels: approved, lgtm, size/S

#121 Bug 1680070: Allow specifying spaces in between packages
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/catalogsourceconfig/cache.go
  pkg/catalogsourceconfig/cache_test.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/registry.go
Labels: approved, lgtm, size/S

#126 Bug 1685331: Update priority for operator
  deploy/operator.yaml
  manifests/10_operator.yaml
Labels: approved, lgtm, size/XS

#123 Bug 1683422: [csc] Make CLI output less verbose
  deploy/crds/catalogsourceconfig.crd.yaml
  deploy/upstream/02_catalogsourceconfig.crd.yaml
  manifests/02_catalogsourceconfig.crd.yaml
Labels: approved, lgtm, size/M

#127 Bug 1685647: Remove unnecessary ClusterRoles
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/upstream/05_role.yaml
  deploy/upstream/06_role_binding.yaml
  manifests/05_role.yaml
  manifests/06_role_binding.yaml
Labels: approved, lgtm, size/L

#124 [docs] Add CONTRIBUTING.md
  CONTRIBUTING.md
  examples/cvo.override.yaml
Labels: approved, lgtm, size/L

#130 Bug 1679284: Properly sync catalogsourceconfigs
  Makefile
  cmd/manager/main.go
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/syncer.go
  pkg/catalogsourceconfig/triggerer.go
  pkg/datastore/datastore.go
  pkg/datastore/update_result.go
  pkg/operatorsource/downloading.go
  pkg/operatorsource/downloading_test.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/handler.go
  pkg/operatorsource/poller.go
  pkg/operatorsource/syncer.go
Labels: approved, lgtm, size/L

#128 Bug 1686121: Update Marketplace management of clusterOperator conditions
  cmd/manager/main.go
  deploy/operator.yaml
  manifests/10_operator.yaml
  manifests/11_clusteroperator.yaml
  pkg/status/status.go
  version/version.go
Labels: approved, lgtm, size/M

#129 update the link of operatorhub UI
  README.md
Labels: approved, lgtm, size/XS

#131 Fix Operator-SDK build
  build/Dockerfile
Labels: approved, lgtm, size/XS

#132 Remove ConfigMap Dependencies
  pkg/catalogsourceconfig/configmapbuilder.go
  pkg/catalogsourceconfig/podtemplatebuilder.go
  pkg/catalogsourceconfig/update.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/phase/phase.go
Labels: approved, lgtm, size/L

#133 Bug 1679284: [csc] Fix PackageRepositoryVersions json string
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
Labels: approved, lgtm, size/XS

#136 Bug 1688703: Properly handle delete failures
  pkg/catalogsourceconfig/deleted.go
  pkg/catalogsourceconfig/handler.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/handler.go
Labels: approved, lgtm, size/M

#135 [docs] Add CLI uninstall flow to README.md
  README.md
Labels: approved, lgtm, size/M

#138 Bug 1686668: [csc] Ignore invalid values when reading `csc.Spec.Packages`
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/catalogsourceconfig/cache.go
  pkg/catalogsourceconfig/registry.go
Labels: approved, lgtm, size/S

#134 Bug 1686121 & 1689443: Update management of clusterOperator
  cmd/manager/main.go
  deploy/role.yaml
  deploy/upstream/05_role.yaml
  manifests/05_role.yaml
  manifests/11_clusteroperator.yaml
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/status/status.go
  pkg/status/syncratio.go
  pkg/status/syncutils.go
Labels: approved, lgtm, size/XL

#140 Bug 1691241: [csc] Don't ignore cache on restart
  pkg/catalogsourceconfig/cache.go
  pkg/catalogsourceconfig/factory.go
Labels: approved, lgtm, size/S

#141 Bug 1691241 [csc] Prevent getting stuck in current state when cache is invalid for csc
  pkg/catalogsourceconfig/update.go
Labels: approved, lgtm, size/M

#145 [e2e] Test CSC with non-existant targetNamespace
  test/e2e/csc_tests.go
  test/e2e/helpers.go
  test/e2e/marketplace_test.go
Labels: approved, lgtm, size/L
