Repository operator-framework/operator-marketplace, pull requests merged in 2019-01, with the labels that each got.

#81 [opsrc] Make configuring reconciler idempotent
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
Labels: approved, lgtm, size/L

#87 Add default operatorsource
  manifests/07_default_operatorsource.cr.yaml
  manifests/08_operator.yaml
Labels: approved, lgtm, size/XS

#84 [opsrc] Add retry logic to opsrc reconciliation
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/downloading.go
  pkg/operatorsource/purging.go
  pkg/operatorsource/validating.go
Labels: approved, lgtm, size/S

#68 [docs] Document operator metadata displayed in the marketplace UI
  docs/how-to-upload-artifact.md
  docs/marketplace-required-csv-annotations.md
Labels: approved, lgtm, size/M

#91 [deploy] Deploy operator to master node
  deploy/marketplace.v0.0.1.clusterserviceversion.yaml
  deploy/operator.yaml
  manifests/10_operator.yaml
Labels: approved, lgtm, size/S

#85 [csc] Add retry logic to csc reconciliation
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/update.go
Labels: approved, lgtm, size/XS

#89 Update catalog when a new version is available
  cmd/manager/main.go
  pkg/apis/marketplace/v1alpha1/catalogsourceconfig_types.go
  pkg/catalogsourceconfig/syncer.go
  pkg/catalogsourceconfig/triggerer.go
  pkg/datastore/datastore.go
  pkg/datastore/metadata.go
  pkg/datastore/row.go
  pkg/datastore/update_result.go
  pkg/operatorsource/poller.go
  pkg/operatorsource/pollhelper.go
  pkg/operatorsource/syncer.go
Labels: approved, lgtm, size/L

#99 [docs] Improve descriptions and add CLI instructions
  README.md
  deploy/examples/catalogsourceconfig.cr.yaml
  deploy/examples/operatorsource.cr.yaml
Labels: approved, lgtm, size/M
