Repository operator-framework/operator-marketplace, pull requests merged in 2019-07, with the labels that each got.

#208 Bug 1723672: Fix owner labels to specify Kind
  pkg/builders/builders.go
  pkg/builders/catalogsourcebuilder.go
  pkg/builders/deploymentbuilder.go
  pkg/builders/rolebindingbuilder.go
  pkg/builders/rolebuilder.go
  pkg/builders/serviceaccountbuilder.go
  pkg/builders/servicebuilder.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/deleted.go
  pkg/grpccatalog/grpccatalog.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/deleted.go
  pkg/registry/registry.go
  test/helpers/helpers.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/opsrccreationtests.go
  test/testsuites/opsrcdeletetests.go
  test/testsuites/packagestests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#214 Bug 1721537: Fix degraded status on upgrade
  cmd/manager/main.go
  deploy/operator.yaml
  deploy/role.yaml
  deploy/upstream/05_role.yaml
  deploy/upstream/08_operator.yaml
  manifests/05_role.yaml
  manifests/10_operator.yaml
  pkg/catalogsourceconfig/handler.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/operatorsource/handler.go
  pkg/status/status.go
  pkg/status/syncutils.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#213 [e2e] Remove hardcoded namespace
  test/testsuites/packagestests.go
Labels: approved, lgtm, size/XS

#215 Bug 1727023: [status] Add upgradeable condition
  pkg/status/status.go
  test/testsuites/clusteroperatorstatustests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#217 Bug 1700100: Stop scaling down registry deployment
  pkg/registry/registry.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#216 Bug 1696726: Don't replace pod spec on updates
  pkg/operatorsource/configuring_test.go
  pkg/registry/registry.go
  test/testsuites/opsrccreationtests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#200 Add watches for deletion of CatalogSourceConfig child resources
  cmd/manager/main.go
  deploy/role.yaml
  deploy/upstream/05_role.yaml
  manifests/05_role.yaml
  pkg/apis/operators/shared/shared.go
  pkg/catalogsourceconfig/factory.go
  pkg/catalogsourceconfig/otherns.go
  pkg/catalogsourceconfig/succeeded.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/otherns.go
  pkg/operatorsource/outofsync.go
  pkg/watches/csc_mapper.go
  pkg/watches/helpers.go
  test/e2e/main_test.go
  test/helpers/helpers.go
  test/testgroups/operatorsourcetests.go
  test/testgroups/opsrccsctests.go
  test/testsuites/cscinvalidtests.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/invalidopsrctests.go
  test/testsuites/packagestests.go
  test/testsuites/watchtests.go
Labels: approved, lgtm, size/XL

#224 [opsrc] Add watches for deletion of child resources
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/succeeded.go
  pkg/watches/helpers.go
  pkg/watches/opsrc_mapper.go
  test/testsuites/watchtests.go
Labels: approved, lgtm, size/L

#228 [opsrc] Fix IsEqual()
  pkg/apis/operators/v1/operatorsource_types.go
Labels: approved, lgtm, size/XS

#211 Bug 1717509: [status] Populate RelatedObjects
  pkg/status/status.go
  test/e2e/main_test.go
  test/testgroups/clusteroperatortests.go
  test/testsuites/clusteroperatorstatustests.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#230 Bug 1732760: Ensure cscs not deleted on operator restart
  pkg/migrator/migrator.go
  test/testgroups/migrationtests.go
  test/testsuites/migrationtests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#233 Bug 1733454: Specify kind in op registry labels
  pkg/registry/registry.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#234 Bug 1732503: Restore default opsrc spec
  pkg/defaults/defaults.go
  pkg/operatorsource/handler.go
  test/testsuites/defaultopsrctests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
