Repository operator-framework/operator-marketplace, pull requests merged in 2020-10, with the labels that each got.

#347 Bug 1885376: Remove condition around marketplace OperatorAvailable status update
  pkg/status/status.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#326 Bug 1872880: Correctly count non-default Marketplace CRs
  pkg/catalogsourceconfig/deleted.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/metrics/metrics.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/initial.go
  pkg/status/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#353 Add bugzilla component to OWNERS file
  OWNERS
Labels: approved, lgtm

#352 remove the unused resyncInterval
  cmd/manager/main.go
Labels: approved, lgtm, ok-to-test

#354 Bug 1838352: Don't report OperatorExited to ClusterOperator
  pkg/status/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
