Repository operator-framework/operator-marketplace, pull requests merged in 2020-01, with the labels that each got.

#276 Bug 1786037: Enable CGO in osbs build target
  build/build.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#277 Use DNS for CatalogSource address
  pkg/registry/registry.go
Labels: approved, lgtm, size/XS

#278 Add marketplace default catalog sources
  defaults/04_redhat_marketplace.yaml
  test/testsuites/operatorhubtests.go
Labels: approved, lgtm, size/M

#280 Bug 1787660: Add CLI flag to set ClusterOperator name.
  cmd/manager/main.go
  deploy/configmap.yaml
  deploy/crds/operators_v1_operatorsource_crd.yaml
  deploy/crds/operators_v2_catalogsourceconfig_crd.yaml
  deploy/marketplace.ns.yaml
  deploy/operator.yaml
  deploy/prometheus_rule.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service.yaml
  deploy/service_account.yaml
  deploy/service_monitor.yaml
  manifests/09_operator.yaml
  pkg/catalogsourceconfig/handler.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/configmap/configmap_controller.go
  pkg/controller/controller.go
  pkg/controller/operatorhub/operatorhub_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/controller/options/options.go
  pkg/operatorsource/handler.go
  pkg/operatorsource/handler_test.go
  pkg/status/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL
