Repository operator-framework/operator-marketplace, pull requests merged in 2020-03, with the labels that each got.

#282 Bug 1801294: Alert to make custom opsrc/csc users aware of deprecation
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/controller/operatorsource/operatorsource_controller.go
  pkg/status/status.go
  test/helpers/helpers.go
  test/testgroups/clusteroperatortests.go
  test/testsuites/clusteroperatorstatustests.go
  test/testsuites/operatorhubtests.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#286 Bug 1809200: enable prometheus metrics over https
  Gopkg.lock
  cmd/manager/main.go
  manifests/08_service.yaml
  manifests/09_operator.yaml
  manifests/11_service_monitor.yaml
  pkg/certificateauthority/caconfigmap.go
  pkg/certificateauthority/handler.go
  pkg/filemonitor/cert_updater.go
  pkg/filemonitor/cert_updater_test.go
  pkg/filemonitor/testdata/ca.crt
  pkg/filemonitor/testdata/cert-config/Makefile
  pkg/filemonitor/testdata/cert-config/csr-new.conf
  pkg/filemonitor/testdata/cert-config/csr-old.conf
  pkg/filemonitor/testdata/cert-config/gen-certs.sh
  pkg/filemonitor/testdata/server-new.crt
  pkg/filemonitor/testdata/server-new.key
  pkg/filemonitor/testdata/server-old.crt
  pkg/filemonitor/testdata/server-old.key
  pkg/filemonitor/watcher.go
  pkg/metrics/metrics.go
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XXL

#288 show the source commit id
  build/build.sh
Labels: approved, lgtm, ok-to-test, size/XS

#256 Bug 1752063: increase initial delay for appregistry pods
  pkg/registry/registry.go
  scripts/e2e-tests.sh
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#290 pkg/status: Fix "DprecatedAPIsInUse" -> "DeprecatedAPIsInUse" typo
  pkg/status/status.go
Labels: approved, lgtm, ok-to-test

#294 Updating the links to crd files
  README.md
Labels: approved, lgtm, ok-to-test

#295 Updating href link to navigate to correct subsection
  README.md
Labels: approved, lgtm, ok-to-test
