Repository operator-framework/operator-marketplace, pull requests merged in 2020-11, with the labels that each got.

#358 Bug 1891993: clean up child resources for old opsrcs
  cmd/manager/main.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#359 Bug 1868770: Allow catsrc with default catsrc name in disconnected env
  pkg/controller/catalogsource/catalogsource_controller.go
  test/testsuites/defaultcatsrctests.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#364 Bug 1896160: Marketplace should report when it is degraded
  pkg/status/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#361 Format logs info
  pkg/controller/catalogsource/catalogsource_controller.go
Labels: approved, lgtm, ok-to-test

#356 Bug 1881542: Set all CO conditions on meeting expected sync ratio
  pkg/status/status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#355 add current profile annotations to CVO manifests
  manifests/01_namespace.yaml
  manifests/04_service_account.yaml
  manifests/05_role.yaml
  manifests/06_role_binding.yaml
  manifests/07_configmap.yaml
  manifests/08_service.yaml
  manifests/09_operator.yaml
  manifests/10_clusteroperator.yaml
  manifests/11_service_monitor.yaml
Labels: approved, lgtm, ok-to-test
