Repository operator-framework/operator-marketplace, pull requests merged in 2020-08, with the labels that each got.

#318 [default] Switch default OperatorSources to CatalogSources
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
  pkg/status/status.go
  pkg/status/syncratio.go
  test/e2e/main_test.go
  test/helpers/helpers.go
  test/testgroups/nosetuptests.go
  test/testgroups/opsrccsctests.go
  test/testsuites/defaultopsrctests.go
  test/testsuites/operatorhubtests.go
Labels: approved, lgtm

#322 Bug 1862481: Correctly count non-default Marketplace CRs
  pkg/metrics/metrics.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/initial.go
  pkg/status/status.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#330 Bug 1871987: Update 03_community_operators.yaml
  defaults/03_community_operators.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#329 Bug 1867821: Include spec.priority for default sources
  cmd/manager/main.go
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
  pkg/apis/olm/v1alpha1/catalogsource_types.go
  pkg/apis/olm/v1alpha1/doc.go
  pkg/apis/olm/v1alpha1/register.go
  pkg/apis/olm/v1alpha1/zz_generated.deepcopy.go
  pkg/builders/catalogsourcebuilder.go
  pkg/defaults/catsrcHelpers.go
  pkg/defaults/defaults.go
  pkg/migrator/migrator.go
  pkg/status/status.go
  test/e2e/main_test.go
  test/helpers/helpers.go
  test/testsuites/operatorhubtests.go
  test/testsuites/watchtests.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#334 Update OWNERS
  OWNERS
Labels: approved, lgtm
