Repository operator-framework/operator-marketplace, pull requests merged in 2020-06, with the labels that each got.

#309 Update OWNERS file with latest team owners
  OWNERS
Labels: approved, lgtm

#313 Bug 1833207: Ensure correct registry image
  pkg/registry/registry.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#303 Bug 1826372: Tigger alert for invalid CSC
  pkg/catalogsourceconfig/initial.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
