Repository operator-framework/operator-marketplace, pull requests merged in 2020-04, with the labels that each got.

#298 [deprecation] Prometheus alert for custom resources
  manifests/12_prometheus_rule.yaml
  pkg/catalogsourceconfig/deleted.go
  pkg/catalogsourceconfig/initial.go
  pkg/metrics/metrics.go
  pkg/operatorsource/deleted.go
  pkg/operatorsource/initial.go
Labels: approved, lgtm

#296 [release-4.3] Bug 1813995: support serving marketplace prometheus metrics over https
  Gopkg.lock
  cmd/manager/main.go
  manifests/08_service.yaml
  manifests/09_operator.yaml
  manifests/11_service_monitor.yaml
  pkg/certificateauthority/caconfigmap.go
  pkg/certificateauthority/handler.go
  pkg/filemonitor/cert_updater.go
  pkg/filemonitor/cert_updater_test.go
  pkg/filemonitor/testdata/ca.crt
  pkg/filemonitor/testdata/cert-config/Makefile
  pkg/filemonitor/testdata/cert-config/csr-new.conf
  pkg/filemonitor/testdata/cert-config/csr-old.conf
  pkg/filemonitor/testdata/cert-config/gen-certs.sh
  pkg/filemonitor/testdata/server-new.crt
  pkg/filemonitor/testdata/server-new.key
  pkg/filemonitor/testdata/server-old.crt
  pkg/filemonitor/testdata/server-old.key
  pkg/filemonitor/watcher.go
  pkg/metrics/metrics.go
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#302 [deprecation]: Deprecate CatalogSourceConfig API
  cmd/manager/main.go
  deploy/examples/catalogsourceconfig.cr.yaml
  deploy/upstream/02_catalogsourceconfig.crd.yaml
  deploy/upstream/03_operatorsource.crd.yaml
  deploy/upstream/05_role.yaml
  docs/csc-source-resolution.md
  manifests/02_catalogsourceconfig.crd.yaml
  manifests/03_operatorsource.crd.yaml
  manifests/05_role.yaml
  manifests/12_prometheus_rule.yaml
  pkg/apis/operators/v1/operatorsource_types.go
  pkg/catalogsourceconfig/cache.go
  pkg/catalogsourceconfig/cache_test.go
  pkg/catalogsourceconfig/configuring.go
  pkg/catalogsourceconfig/deleted.go
  pkg/catalogsourceconfig/factory.go
  pkg/catalogsourceconfig/failed.go
  pkg/catalogsourceconfig/handler.go
  pkg/catalogsourceconfig/initial.go
  pkg/catalogsourceconfig/otherns.go
  pkg/catalogsourceconfig/reconciler.go
  pkg/catalogsourceconfig/succeeded.go
  pkg/catalogsourceconfig/syncer.go
  pkg/catalogsourceconfig/triggerer.go
  pkg/catalogsourceconfig/update.go
  pkg/controller/add_catalogsourceconfig.go
  pkg/controller/catalogsourceconfig/catalogsourceconfig_controller.go
  pkg/metrics/metrics.go
  pkg/migrator/migrator.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/helper_test.go
  pkg/status/status.go
  pkg/watches/csc_mapper.go
  pkg/watches/helpers.go
  test/e2e/main_test.go
  test/helpers/helpers.go
  test/testgroups/clusteroperatortests.go
  test/testgroups/opsrccsctests.go
  test/testsuites/clusteroperatorstatustests.go
  test/testsuites/cscinvalidtests.go
  test/testsuites/csctargetnamespacetests.go
  test/testsuites/opsrccreationtests.go
  test/testsuites/packagestests.go
  test/testsuites/proxytests.go
  test/testsuites/watchtests.go
Labels: approved, lgtm

#297 [release-4.2] Bug 1814012: support serving marketplace prometheus metrics over https
  Gopkg.lock
  cmd/manager/main.go
  manifests/08_service.yaml
  manifests/09_operator.yaml
  manifests/11_service_monitor.yaml
  pkg/certificateauthority/caconfigmap.go
  pkg/certificateauthority/handler.go
  pkg/filemonitor/cert_updater.go
  pkg/filemonitor/cert_updater_test.go
  pkg/filemonitor/testdata/ca.crt
  pkg/filemonitor/testdata/cert-config/Makefile
  pkg/filemonitor/testdata/cert-config/csr-new.conf
  pkg/filemonitor/testdata/cert-config/csr-old.conf
  pkg/filemonitor/testdata/cert-config/gen-certs.sh
  pkg/filemonitor/testdata/server-new.crt
  pkg/filemonitor/testdata/server-new.key
  pkg/filemonitor/testdata/server-old.crt
  pkg/filemonitor/testdata/server-old.key
  pkg/filemonitor/watcher.go
  pkg/metrics/metrics.go
  pkg/version/version.go
  vendor/github.com/fsnotify/fsnotify/AUTHORS
  vendor/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/fsnotify/fsnotify/fen.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/inotify.go
  vendor/github.com/fsnotify/fsnotify/inotify_poller.go
  vendor/github.com/fsnotify/fsnotify/kqueue.go
  vendor/github.com/fsnotify/fsnotify/open_mode_bsd.go
  vendor/github.com/fsnotify/fsnotify/open_mode_darwin.go
  vendor/github.com/fsnotify/fsnotify/windows.go
Labels: approved, bugzilla/medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#304 Bug 1827676: Fix panic when default Catsrc polling is not set
  pkg/defaults/catsrcHelpers.go
Labels: approved, bugzilla/unspecified, bugzilla/valid-bug, lgtm
