Repository operator-framework/operator-marketplace, pull requests merged in 2020-09, with the labels that each got.

#332 Bug 1874751: Add OKD-specific Dockerfile
  Dockerfile.okd
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#336 Bug 1873250: Recreate default CatalogSources if deleted/edited
  cmd/manager/main.go
  pkg/controller/add_catalogsource.go
  pkg/controller/catalogsource/catalogsource_controller.go
  test/helpers/helpers.go
  test/testgroups/nosetuptests.go
  test/testsuites/defaultcatsrctests.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#337 Bug 1874751: Dockerfile.okd: switch to root user when updating manifests
  Dockerfile.okd
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, ok-to-test

#340 Bug 1877564: Sync remote app-registry
  Makefile
  cmd/manager/main.go
  pkg/operatorsource/configuring.go
  pkg/operatorsource/configuring_test.go
  pkg/operatorsource/factory.go
  pkg/operatorsource/handler.go
  pkg/operatorsource/poller.go
  pkg/operatorsource/syncer.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#335 Bug 1873546: Increase registry delay for large payloads
  pkg/registry/registry.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#346 Bug 1881713: Poll for CatalogSources in operatorhub test
  test/testsuites/operatorhubtests.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
