Repository operator-framework/operator-marketplace, pull requests merged in 2021-04, with the labels that each got.

#385 Add ROKS profile annotation
  manifests/01_namespace.yaml
  manifests/04_service_account.yaml
  manifests/05_role.yaml
  manifests/06_role_binding.yaml
  manifests/07_configmap.yaml
  manifests/08_service.yaml
  manifests/09_operator.yaml
  manifests/10_clusteroperator.yaml
  manifests/11_service_monitor.yaml
Labels: approved, lgtm, ok-to-test

#386 Build with Go 1.16
  Dockerfile.rhel7
  Makefile
  build/build.sh
Labels: approved, lgtm, ok-to-test

#388 Add management workload annotations
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
  manifests/01_namespace.yaml
  manifests/09_operator.yaml
Labels: approved, lgtm, ok-to-test

#387 update defaults to 4.8
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
Labels: approved, lgtm

#390 Bug 1947794: Update openshift rolebindings to v1
  manifests/06_role_binding.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#392 Update Dockerfile.okd
  Dockerfile.okd
Labels: approved, bugzilla/valid-bug, lgtm

#394 Bug 1950417: Add the ability to override the operator-sdk binary in e2e tests
  scripts/e2e-tests.sh
  scripts/run-e2e-job.sh
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#395 Bug 1946790: Update clusteroperator status conditions on startup
  pkg/status/status.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#393 Rename workload annotations
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
  manifests/09_operator.yaml
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test
