Repository operator-framework/operator-marketplace, pull requests merged in 2021-09, with the labels that each got.

#425 Makefile,test: Fix flaky e2e tests
  Makefile
  test/e2e/clusteroperator_test.go
  test/e2e/operatorhub_test.go
Labels: lgtm, approved

#409 Bug 1961341: [release-4.7] Update openshift rolebindings to v1
  manifests/06_role_binding.yaml
Labels: lgtm, approved, ok-to-test, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium

#421 [release-4.8] Bug 1998938: Use client-go's leader election implementation
  cmd/manager/main.go
  manifests/05_role.yaml
  pkg/defaults/catsrcHelpers.go
  pkg/defaults/defaults.go
  pkg/migrator/migrator.go
  pkg/signals/signals.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
  vendor/modules.txt
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high

#424 Remove unused packages
  pkg/builders/builders.go
  pkg/builders/catalogsourcebuilder.go
  pkg/builders/deploymentbuilder.go
  pkg/builders/rolebindingbuilder.go
  pkg/builders/rolebuilder.go
  pkg/builders/serviceaccountbuilder.go
  pkg/builders/servicebuilder.go
  pkg/metrics/roundtripper.go
Labels: lgtm, approved

#426 Remove the marketplace v1 and v2 APIs
  Makefile
  cmd/manager/main.go
  hack/openapi-gen.sh
  pkg/apis/addtoscheme_operators_v1.go
  pkg/apis/addtoscheme_operators_v2.go
  pkg/apis/operators/v1/doc.go
  pkg/apis/operators/v1/operatorsource_types.go
  pkg/apis/operators/v1/register.go
  pkg/apis/operators/v1/zz_generated.deepcopy.go
  pkg/apis/operators/v1/zz_generated.openapi.go
  pkg/apis/operators/v2/catalogsourceconfig_types.go
  pkg/apis/operators/v2/doc.go
  pkg/apis/operators/v2/register.go
  pkg/apis/operators/v2/zz_generated.deepcopy.go
  pkg/apis/operators/v2/zz_generated.openapi.go
  pkg/certificateauthority/handler.go
  pkg/client/client.go
  pkg/controller/catalogsource/catalogsource_controller.go
  pkg/controller/operatorhub/operatorhub_controller.go
  pkg/defaults/defaults.go
  pkg/defaults/opsrcHelpers.go
  pkg/operatorhub/handler.go
  pkg/operatorhub/operatorhub.go
  pkg/status/status.go
  test/e2e/suite_test.go
Labels: lgtm, approved

#429 Add summary and description for prometheus alerts
  manifests/12_prometheus_rule.yaml
Labels: lgtm, approved
