Repository operator-framework/operator-marketplace, pull requests merged in 2022-06, with the labels that each got.

#474 Bug 2092464: shift marketplace operator catalogs default to v4.11
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#476 Revert "Bug 2092464: shift marketplace operator catalogs default to v4.11"
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#470 Bug 2079610: Fix operatorHub status
  pkg/defaults/catsrcHelpers.go
  test/e2e/operatorhub_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium, qe-approved

#477 Bug 2092464: Update default catalogsource to use 4.11 images
  defaults/01_redhat_operators.cr.yaml
  defaults/02_certified_operators.yaml
  defaults/03_community_operators.yaml
  defaults/04_redhat_marketplace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#478 Bug 2088541: Add psa anotations to namespace to suppress warnings
  manifests/01_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent
