Repository operator-framework/operator-marketplace, pull requests merged in 2022-04, with the labels that each got.

#401 manifests/10_clusteroperator: Drop the unused namespace property
  manifests/10_clusteroperator.yaml
Labels: lgtm, approved, ok-to-test

#465 Bug 2070792: chore(manifests): add missing capabilities annotation
  manifests/08_service.yaml
  manifests/09_operator-ibm-cloud-managed.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#467 fix(capabilities): add operatorhub crd manifest
  Dockerfile
  Dockerfile.okd
  Dockerfile.rhel7
Labels: lgtm, approved

#468 fix(manifests): add singleton operatorhub cr
  manifests/0000_03_marketplace-operator_02_operatorhub.cr.yaml
Labels: lgtm, approved

#461 Bug 2057558: increase polling time of status report to reduce log spam
  cmd/manager/main.go
  pkg/status/status.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low, qe-approved
