Repository operator-framework/operator-marketplace, pull requests merged in 2023-06, with the labels that each got.

#519 OCPBUGS-14109: Revert default catsrc diff changes
  pkg/defaults/catsrcHelpers.go
  test/e2e/operatorhub_test.go
Labels: lgtm, approved, cherry-pick-approved, qe-approved, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#520 OCPBUGS-9357: remove a race condition
  cmd/manager/main.go
Labels: lgtm, approved, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#517 Update owners
  OWNERS
Labels: lgtm, approved, bugzilla/valid-bug

#524 OCPBUGS-13910: update community-operator-index to 4.14 tag
  defaults/03_community_operators.yaml
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference
