Repository operator-framework/operator-marketplace, pull requests merged in 2023-01, with the labels that each got.

#495 OCPBUGS-4873: Add audit-version and warn-version labels
  manifests/01_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, qe-approved, jira/valid-bug, jira/severity-low

#502 OCPBUGS-5423: Remove PSA audit and warnings
  manifests/01_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, jira/valid-bug, jira/severity-critical

#503 [release-4.12] OCPBUGS-5468: Remove PSA audit and warnings
  manifests/01_namespace.yaml
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/severity-critical
