Repository operator-framework/operator-marketplace, pull requests merged in 2024-07, with the labels that each got.

#570 [release-4.15] OCPBUGS-37524: Set required-scc for openshift workloads
  manifests/09_operator-ibm-cloud-managed.yaml
  manifests/09_operator.yaml
Labels: lgtm, approved, ok-to-test, cherry-pick-approved, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#568 OCPBUGS-34244: Updating marketplace-operator-container image to be consistent with ART for 4.17
  .ci-operator.yaml
  Dockerfile
  Dockerfile.okd
  go.mod
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#482 NO-ISSUE: Add client certificate and key to service monitor
  manifests/11_service_monitor.yaml
Labels: lgtm, approved, ok-to-test, jira/valid-reference
